source 'http://rubygems.org'

ruby '2.4.1'

  gem 'bcrypt'
  gem 'capybara'
  gem 'database_cleaner'
  gem 'data_mapper'
  gem 'dm-migrations'
  gem 'dm-postgres-adapter'
  gem 'dm-transactions'
  gem 'rake'
  gem 'rspec'
  gem 'rubocop'
  gem 'sinatra'
  gem 'sinatra-flash'
